var showmenuheight=parseInt($(document).innerHeight()-180);$(document).ready(function(){$("#myTab a").click(function(){$(this).tab("show")});fetchmenu();$("#name-menu, #budget-menu").keyup(sortmenu)});$(window).load(function(){clearall()});var historytab=0;function showhistorytab(){$(".loading-cont").show();setTimeout(function(){$(".loading-cont").hide();$(".history-box-cont").show();historytab=1;$("#clear g").html("Home");$("#history").scrollTop($("#history")[0].scrollHeight)},400)}
function hidehistorytab(){$(".history-box-cont").hide();historytab=0;$("#clear g").html("Clear All")}function coverttotime(c){var b="am";te=c.split(":");12<te[0]&&(te[0]-=12,b="pm");return te[0]+":"+te[1]+" "+b}
$(document).on("change",".quan",function(){foods=$("#show-menu div .name");quantity=$("#show-menu div .quan");costs=$("#show-menu div .cost");for(var c=0,b="",a=0;a<foods.length;a++){if(0<parseInt(quantity[a].value)){costi=parseInt(costs[a].innerHTML);for(var b=b+('<div class="fooditem no-margin"><span class="name" id="name">'+foods[a].innerHTML+'</span><span class=""> x '+parseInt(quantity[a].value)+' </span><span class="cost" id="cost"> '+costi*parseInt(quantity[a].value)+" Rs</span></div>"),c=
c+costi*parseInt(quantity[a].value),e=!1,d=0;d<arrayofselecteditems.length;d++)if(foods[a].innerHTML==arrayofselecteditems[d].name){e=!0;parseInt(quantity[a].value)!=arrayofselecteditems[d].quantity&&(arrayofselecteditems[d].quantity=parseInt(quantity[a].value));break}0==e&&update_arrayofselecteditems(foods[a].innerHTML,parseInt(quantity[a].value),costi*parseInt(quantity[a].value))}else for(d=0;d<arrayofselecteditems.length;d++)if(foods[a].innerHTML==arrayofselecteditems[d].name){arrayofselecteditems.splice(d,
1);break}0==parseInt(quantity[a].value)?$("#fooditem"+a+" .quan").css({"border-bottom":"2px solid #81CFE0"}):$("#fooditem"+a+" .quan").css({"border-bottom":"2px solid #D91E18"})}$("#total").html(c);""==b&&(b='<div class="fooditem no-margin"><span class="name" id="name">Please Select Some Food Items By clicking on the Right of the Food item!</span></div>');$("#what").html(b);$("#what").append('<div class="fooditem total-css"><span class="name" id="name">Total</span><span class="cost" id="cost">'+c+
" Rs</span></div>")});$(window).resize(function(){responsiveness()});
function responsiveness(){showmenuheight=parseInt($(document).innerHeight()-180);$("#show-menu").css("height",showmenuheight-50+"px");$(".selected-box").css("height",showmenuheight+56+"px");$(".loading").css("height",showmenuheight+56+"px");$(".history-box").css("height",showmenuheight+59+56+"px");$("#history").css("height",showmenuheight+-30-58+"px");$("#history").scrollTop($("#history")[0].scrollHeight);400>$(window).width()&&($(".title").css({display:"none"}),$("#name-menu").attr("placeholder",
"Type Food!"),$("#budget-menu").attr("placeholder","Enter Budget"))}function showselected(){$(".loading-cont").show();setTimeout(function(){$(".loading-cont").hide();$(".selected-box-cont").show();$("#confirm-text").html("Back");togglebool=0},400)}function hideselected(){$(".selected-box-cont").hide();$(".loading-cont").hide();$("#confirm-text").html("Click to Confirm");togglebool=1}
function clearall(){showallitems();showselitems=0;$("#showselecteditems span").html("Show Only Selected Items");fetchmenu();$("#what").html('<div class="fooditem no-margin"><span class="name" id="name">Please Select Some Food Items By clicking on the Right of the Food item!</span></div>');$("#total").html(0);hideselected();arrayofselecteditems=[];booleanconfirm=0;$("#budget-menu").val("");$("#name-menu").val("")}
function sortmenu(){var c=$("#name-menu").val().toLowerCase(),b=$("#budget-menu").val();showallitems();showselitems=0;$("#showselecteditems span").html("Show Only Selected Items");$(".category").css({display:"none"});for(var a=0;a<menu.length;a++){$("#fooditem"+a).css({display:"none"});var e=menu[a].category.replace(/ /g,"");!(menu[a].cost<=b||""==b)||-1==menu[a].name.toLowerCase().indexOf(c)&&""!=c||($("#fooditem"+a).css({display:"block"}),$("#"+e).css({display:"block"}))}}
var categorycolors=["#F89406","#F64747","#00B16A","#674172","#DB0A5B"];
function fetchmenu(){var c="",b="";for(i=0;i<menu.length;i++){if(menu[i].category!=c)var c=menu[i].category,a=menu[i].category.replace(/ /g,""),b=b+('<div class="category" id="'+a+'"><span>'+c+"</span></div>");c==menu[i].category&&(b+='<div class="fooditem" id="fooditem'+i+'"><i id="reset'+i+'" class="reset glyphicon glyphicon-remove-circle"></i><span class="name" id="name">'+menu[i].name+"</span>"+options(i)+'<span class="cost" id="cost">'+menu[i].cost+" Rs. </span></div>")}$(".main-content").width();
$("#show-menu").html(b);responsiveness();$("#show-menu").show(500);changecategorycolor()}function showselecteditems(){var c=$("#show-menu .quan");$(".category").css({display:"none"});for(var b=0;b<c.length;b++)if(0==parseInt(c[b].value))$("#fooditem"+b).hide();else{var a=menu[b].category.replace(/ /g,"");$("#"+a).css({display:"block"})}}function showallitems(){$(".category").show();$(".fooditem").show()}
function changecategorycolor(){for(var c=0;c<menu.length;c++){var b=Math.ceil(500*Math.random())%categorycolors.length,a=menu[c].category.replace(/ /g,"");$("#"+a).css("background-color",categorycolors[b])}}
function options(c){return'<select class="quan" id="quan'+c+'"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option></select>'};